# Generated by Django 5.2.6 on 2025-09-19 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
