# Generated by Django 5.2.6 on 2025-09-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
