# Generated by Django 5.2.6 on 2025-09-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
